known_papers:
  - "CNN-generated images are surprisingly easy to spot... for now"
  - "Towards Universal Fake Image Detectors that Generalize Across Generative Models"
  - "DIRE for Diffusion-Generated Image Detection"
  - "FIRE: Robust Detection of Diffusion-Generated Images via Frequency-Guided Reconstruction Error"
  - "GenImage: A Million-Scale Benchmark for Detecting AI-Generated Image"
  - "AIGIBench"
  - "ForenSynths"
  - "Synthbuster"
  - "Detecting GAN generated Fake Images using Co-occurrence Matrices"
  - "Learning on Gradients: Generalized Artifacts Representation for GAN-Generated Images Detection"
  - "UniversalFakeDetect"
  - "Raising the Bar of AI-generated Image Detection with CLIP"
  - "A Bias-Free Training Paradigm for More General AI-generated Image Detection"
  - "Any-Resolution AI-Generated Image Detection by Spectral Learning"
  - "OmniAID"
  - "D3QE"
  - "FakeShield"
  - "AIGI-Holmes"
